from fastapi import APIRouter
from pydantic import BaseModel
from typing import Any, Optional
import time
import random
from datetime import datetime

router = APIRouter()


class PipelineNode(BaseModel):
    id: str
    type: str
    config: dict[str, Any]
    position: dict[str, float]


class PipelineEdge(BaseModel):
    source: str
    target: str


class PipelineRunRequest(BaseModel):
    nodes: list[PipelineNode]
    edges: list[PipelineEdge]


class CodeGenRequest(BaseModel):
    nodes: list[PipelineNode]
    edges: list[PipelineEdge]


@router.post("/pipeline/run")
def run_pipeline(body: PipelineRunRequest):
    steps = []
    input_rows = random.randint(40000, 60000)
    current_rows = input_rows

    node_order = _topological_sort(body.nodes, body.edges)

    for node in node_order:
        start_time = time.time()
        step_duration = round(random.uniform(0.1, 2.5), 3)
        output_rows = current_rows

        log_messages = []

        if node.type == "source":
            table = node.config.get("table", "fact_orders")
            log_messages = [
                f"Connecting to source: {table}",
                f"Reading schema: {random.randint(5, 15)} columns detected",
                f"Extracted {current_rows:,} rows",
            ]
        elif node.type == "filter":
            condition = node.config.get("condition", "status = 'completed'")
            dropped = random.randint(int(current_rows * 0.1), int(current_rows * 0.4))
            output_rows = current_rows - dropped
            log_messages = [
                f"Applying filter: WHERE {condition}",
                f"Filtered out {dropped:,} rows",
                f"Remaining: {output_rows:,} rows",
            ]
        elif node.type == "join":
            right_table = node.config.get("right_table", "dim_customer")
            join_type = node.config.get("join_type", "LEFT JOIN")
            extra = random.randint(0, 500)
            output_rows = current_rows + extra
            log_messages = [
                f"Executing {join_type} with {right_table}",
                f"Join key: {node.config.get('on', 'customer_id')}",
                f"Output: {output_rows:,} rows (+{extra} from join expansion)",
            ]
        elif node.type == "aggregate":
            group_by = node.config.get("group_by", "category")
            agg_fn = node.config.get("aggregation", "SUM(revenue)")
            output_rows = random.randint(10, 500)
            log_messages = [
                f"Grouping by: {group_by}",
                f"Aggregating: {agg_fn}",
                f"Reduced to {output_rows:,} groups",
            ]
        elif node.type == "rename":
            mappings = node.config.get("mappings", {})
            log_messages = [
                f"Renaming {len(mappings)} columns",
                f"Applied: {', '.join([f'{k}→{v}' for k, v in list(mappings.items())[:3]])}",
            ]
        elif node.type == "sink":
            dest = node.config.get("destination", "gold.fact_daily_revenue")
            mode = node.config.get("write_mode", "overwrite")
            log_messages = [
                f"Writing {current_rows:,} rows to {dest}",
                f"Write mode: {mode}",
                f"Created partition key: {node.config.get('partition_by', 'date')}",
                f"Committed successfully",
            ]
        else:
            log_messages = [f"Executing node: {node.type}"]

        steps.append({
            "node_id": node.id,
            "node_type": node.type,
            "input_rows": current_rows,
            "output_rows": output_rows,
            "duration_seconds": step_duration,
            "logs": log_messages,
            "status": "success",
            "schema_preview": _get_sample_schema(node.type),
            "data_preview": _get_sample_rows(node.type, output_rows),
        })
        current_rows = output_rows

    total_duration = sum(s["duration_seconds"] for s in steps)
    return {
        "run_id": f"RUN-{datetime.now().strftime('%Y%m%d%H%M%S')}",
        "status": "success",
        "total_duration_seconds": round(total_duration, 3),
        "input_rows": input_rows,
        "output_rows": current_rows,
        "steps": steps,
        "completed_at": datetime.now().isoformat(),
    }


@router.post("/pipeline/generate-code")
def generate_code(body: CodeGenRequest):
    lines = [
        "import pandas as pd",
        "import sqlite3",
        "from datetime import datetime",
        "",
        "# Generated by Senior Data Engineer Workbench",
        f"# Pipeline generated at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "def run_pipeline():",
        "    print('Starting pipeline execution...')",
        "    conn = sqlite3.connect('workbench.db')",
        "",
    ]

    node_vars = {}
    node_order = _topological_sort(body.nodes, body.edges)

    for i, node in enumerate(node_order):
        var_name = f"df_{node.type}_{i}"
        node_vars[node.id] = var_name

        if node.type == "source":
            table = node.config.get("table", "fact_orders")
            lines += [
                f"    # Step {i+1}: Extract from source",
                f"    {var_name} = pd.read_sql('SELECT * FROM {table}', conn)",
                f"    print(f'Extracted {{len({var_name}):,}} rows from {table}')",
                "",
            ]
        elif node.type == "filter":
            cond = node.config.get("pandas_condition", "df['status'] == 'completed'")
            prev_var = _get_prev_var(node.id, body.edges, node_vars)
            lines += [
                f"    # Step {i+1}: Filter rows",
                f"    {var_name} = {prev_var}[{cond}].copy()",
                f"    print(f'Filter: {{len({var_name}):,}} rows remaining')",
                "",
            ]
        elif node.type == "join":
            right = node.config.get("right_table", "dim_customer")
            on = node.config.get("on", "customer_id")
            how = node.config.get("join_type", "left").lower().replace(" join", "")
            prev_var = _get_prev_var(node.id, body.edges, node_vars)
            lines += [
                f"    # Step {i+1}: Join with {right}",
                f"    dim = pd.read_sql('SELECT * FROM {right}', conn)",
                f"    {var_name} = {prev_var}.merge(dim, on='{on}', how='{how}')",
                f"    print(f'After join: {{len({var_name}):,}} rows')",
                "",
            ]
        elif node.type == "aggregate":
            group_by = node.config.get("group_by", "category")
            agg_col = node.config.get("agg_column", "revenue")
            agg_fn = node.config.get("agg_function", "sum")
            prev_var = _get_prev_var(node.id, body.edges, node_vars)
            lines += [
                f"    # Step {i+1}: Aggregate",
                f"    {var_name} = {prev_var}.groupby('{group_by}')['{agg_col}'].{agg_fn}().reset_index()",
                f"    {var_name}.columns = ['{group_by}', '{agg_fn}_{agg_col}']",
                f"    print(f'Aggregated to {{len({var_name}):,}} groups')",
                "",
            ]
        elif node.type == "rename":
            mappings = node.config.get("mappings", {"revenue": "total_revenue"})
            prev_var = _get_prev_var(node.id, body.edges, node_vars)
            lines += [
                f"    # Step {i+1}: Rename columns",
                f"    {var_name} = {prev_var}.rename(columns={mappings})",
                "",
            ]
        elif node.type == "sink":
            dest = node.config.get("destination", "gold_daily_revenue")
            mode = "replace" if node.config.get("write_mode", "overwrite") == "overwrite" else "append"
            prev_var = _get_prev_var(node.id, body.edges, node_vars)
            lines += [
                f"    # Step {i+1}: Load to destination",
                f"    {prev_var}['updated_at'] = datetime.now().isoformat()",
                f"    {prev_var}.to_sql('{dest}', conn, if_exists='{mode}', index=False)",
                f"    print(f'Loaded {{len({prev_var}):,}} rows to {dest}')",
                "",
            ]

    lines += [
        "    conn.close()",
        "    print('Pipeline completed successfully!')",
        "",
        "",
        "if __name__ == '__main__':",
        "    run_pipeline()",
    ]

    return {"code": "\n".join(lines), "language": "python"}


@router.get("/pipeline/templates")
def get_templates():
    return {
        "templates": [
            {
                "id": "etl-orders",
                "name": "Orders ETL Pipeline",
                "description": "Extract orders, join with customers, aggregate daily revenue",
                "nodes": [
                    {"id": "n1", "type": "source", "config": {"table": "fact_orders"}, "position": {"x": 50, "y": 200}},
                    {"id": "n2", "type": "filter", "config": {"condition": "status = 'completed'", "pandas_condition": "df['status'] == 'completed'"}, "position": {"x": 250, "y": 200}},
                    {"id": "n3", "type": "join", "config": {"right_table": "dim_customer", "on": "customer_id", "join_type": "LEFT"}, "position": {"x": 450, "y": 200}},
                    {"id": "n4", "type": "aggregate", "config": {"group_by": "category", "agg_column": "revenue", "agg_function": "sum"}, "position": {"x": 650, "y": 200}},
                    {"id": "n5", "type": "sink", "config": {"destination": "gold_daily_revenue", "write_mode": "overwrite", "partition_by": "date"}, "position": {"x": 850, "y": 200}},
                ],
                "edges": [
                    {"source": "n1", "target": "n2"},
                    {"source": "n2", "target": "n3"},
                    {"source": "n3", "target": "n4"},
                    {"source": "n4", "target": "n5"},
                ],
            }
        ]
    }


def _topological_sort(nodes: list, edges: list) -> list:
    adj = {n.id: [] for n in nodes}
    in_deg = {n.id: 0 for n in nodes}
    for e in edges:
        adj[e.source].append(e.target)
        in_deg[e.target] += 1

    queue = [n for n in nodes if in_deg[n.id] == 0]
    result = []
    while queue:
        node = queue.pop(0)
        result.append(node)
        for neighbor in adj[node.id]:
            in_deg[neighbor] -= 1
            if in_deg[neighbor] == 0:
                next_node = next((n for n in nodes if n.id == neighbor), None)
                if next_node:
                    queue.append(next_node)
    return result or nodes


def _get_prev_var(node_id: str, edges: list, node_vars: dict) -> str:
    for e in edges:
        if e.target == node_id and e.source in node_vars:
            return node_vars[e.source]
    return "df"


def _get_sample_schema(node_type: str) -> list:
    schemas = {
        "source": [{"col": "order_id", "type": "VARCHAR"}, {"col": "customer_id", "type": "VARCHAR"}, {"col": "revenue", "type": "DECIMAL"}],
        "filter": [{"col": "order_id", "type": "VARCHAR"}, {"col": "customer_id", "type": "VARCHAR"}, {"col": "revenue", "type": "DECIMAL"}],
        "join": [{"col": "order_id", "type": "VARCHAR"}, {"col": "customer_id", "type": "VARCHAR"}, {"col": "first_name", "type": "VARCHAR"}, {"col": "revenue", "type": "DECIMAL"}],
        "aggregate": [{"col": "category", "type": "VARCHAR"}, {"col": "sum_revenue", "type": "DECIMAL"}, {"col": "order_count", "type": "INTEGER"}],
        "rename": [{"col": "category", "type": "VARCHAR"}, {"col": "total_revenue", "type": "DECIMAL"}],
        "sink": [{"col": "category", "type": "VARCHAR"}, {"col": "total_revenue", "type": "DECIMAL"}, {"col": "updated_at", "type": "TIMESTAMP"}],
    }
    return schemas.get(node_type, [])


def _get_sample_rows(node_type: str, row_count: int) -> list:
    if node_type in ["aggregate", "sink"]:
        return [
            {"category": "Electronics", "total_revenue": 125430.50, "order_count": 892},
            {"category": "Clothing", "total_revenue": 87234.10, "order_count": 1243},
            {"category": "Home & Garden", "total_revenue": 54890.75, "order_count": 673},
        ]
    return [
        {"order_id": "ORD-001234", "customer_id": "CUST-00045", "revenue": 149.99, "status": "completed"},
        {"order_id": "ORD-001235", "customer_id": "CUST-00102", "revenue": 89.50, "status": "completed"},
        {"order_id": "ORD-001236", "customer_id": "CUST-00008", "revenue": 299.00, "status": "shipped"},
    ]
